name: tf-checks action

on:
  push:
    branches:
      - 'main'

  pull_request:

  workflow_dispatch:

jobs:
  tf-static-checks:
    uses: h1manshu98/testing-shared-workflow/.github/workflows/caller.yml@main
    with:  
        working_directory: './terraform/'
        init: true
        validate: true
        plan: true